name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          cache-dependency-glob: "uv.lock"

      - name: Check uv version
        run: uv --version

      - name: List resolved dependencies
        run: uv pip list

      - name: Run uv lock
        run: uv lock || true # Continue even if it fails

      - name: Show lockfile diff
        run: git diff uv.lock || true

      - name: Sync dependencies with debug
        run: UV_DEBUG=1 uv sync --locked || true

      - name: Print environment variables
        run: env | sort

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build distribution files
        run: uv run make build
        shell: bash

      - name: Publish package to PyPI (using uv run)
        run: uv run make publish
        shell: bash

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          cache-dependency-glob: "uv.lock"

      - name: Sync dependencies
        run: uv sync --locked

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
