name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the UV environment
        uses: ./.github/actions/setup-uv-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build distribution files
        run: make build
        shell: bash

      - name: Publish package to PyPI (using uv via Make)
        run: make publish
        shell: bash

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the UV environment
        uses: ./.github/actions/setup-uv-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
